FROM centos:7
MAINTAINER Marcus R. Breese <marcus@breese.com>

RUN yum update -y && yum install -y gcc make ncurses-devel zlib-devel tar bzip2 && yum clean all

RUN cd /tmp && \
    curl -OL https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2 && \
    tar xf samtools-1.2.tar.bz2 && cd samtools-1.2 &&\
    make && make install && \
    cd / && rm -rf /tmp/samtools-1.2*
